refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} | {m}{n}"
  logfile:
    kind: file
    path: "log/logfile.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} | {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - logfile